### Запуск QtLab

In [1]:
%run D:\qtlab_replacement\init.py
%matplotlib qt5
import matplotlib.pyplot as plt
from instruments import *
import numpy as np
import sweep
from save_pkl import *
import visa
#import pikle
from matplotlib  import interactive
interactive(True)

Failed loading module Labbrick:  [WinError 126] The specified module could not be found
Failed loading module Signal_Hound_SA:  [WinError 126] The specified module could not be found


In [2]:
from resonator_tools import circuit

In [3]:
import pylab
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import LinearSegmentedColormap
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pickle

import numpy as np
#%matplotlib inline
from matplotlib import pyplot as plt
import matplotlib.ticker

# Спектроскопия

In [4]:
current_src = Yokogawa_GS210(address='gs210')
#current = Yokogawa_GS210(address='gs210')
pna = Agilent_N5242A('pna', address = 'PNA')
lo1 = Agilent_E8257D('lo1', address = 'PSG1')

In [5]:
# векторный анализатор в режим линейного свипа
pna.set_sweep_mode("LIN")

True

## Резонаторная спектроскопия

In [9]:
current_src.set_current(250e-5)
pna.set_power(-30)

True

In [ ]:
current_src.set_status(1)

In [ ]:
pna.set_autoscale()

In [10]:
pna.set_centerfreq(3.176453e9)
pna.set_span(200e6)
pna.set_bandwidth(100)
pna.set_averages(1)
pna.set_nop(300)
pna.set_power(-30)

True

In [11]:
currents = np.linspace(150e-6, 350e-6, 201)
pna.set_xlim(3.17e9, 3.18e9)
pna.set_bandwidth(100)
pna.set_averages(1)
pna.set_nop(101)
pna.set_power(-30)
sweep.sweep(pna, (currents, current_src.set_current, 'Coil current'), filename='Acouston_2 spectrum_-30dB')

Started at:  May 15 2017 16:16:38


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Coil current: 0.00035,	average cycle time:  1.5s				
Elapsed time: 0 h 5 m 1.02 s


{'S-parameter': (('Coil current', 'Frequency'),
  (array([ 0.00015 ,  0.000151,  0.000152,  0.000153,  0.000154,  0.000155,
           0.000156,  0.000157,  0.000158,  0.000159,  0.00016 ,  0.000161,
           0.000162,  0.000163,  0.000164,  0.000165,  0.000166,  0.000167,
           0.000168,  0.000169,  0.00017 ,  0.000171,  0.000172,  0.000173,
           0.000174,  0.000175,  0.000176,  0.000177,  0.000178,  0.000179,
           0.00018 ,  0.000181,  0.000182,  0.000183,  0.000184,  0.000185,
           0.000186,  0.000187,  0.000188,  0.000189,  0.00019 ,  0.000191,
           0.000192,  0.000193,  0.000194,  0.000195,  0.000196,  0.000197,
           0.000198,  0.000199,  0.0002  ,  0.000201,  0.000202,  0.000203,
           0.000204,  0.000205,  0.000206,  0.000207,  0.000208,  0.000209,
           0.00021 ,  0.000211,  0.000212,  0.000213,  0.000214,  0.000215,
           0.000216,  0.000217,  0.000218,  0.000219,  0.00022 ,  0.000221,
           0.000222,  0.000223,  0.00022

In [ ]:
plt.plot(20*np.log10(pna.get_freqpoints()[0]))

In [137]:
res_data = pna.get_tracedata()
res_freqs = pna.get_freqpoints()
plt.figure("S21_amp")
plt.plot(res_freqs, 20*np.log10(res_data[0]))
plt.figure("S21_ph")
plt.plot(res_freqs, res_data[1])
#save_pkl_noplt('res_pna_', {"Amp": res_data[0] , "Ph": res_data[1], "freqs": res_freqs } )

In [ ]:
dir = "D:/qtlab/ReiData/data/2017-05-09/"

In [ ]:
plt.ioff()
path = get_location()
mk_dir()
fig_path = path[0]+"\\"+path[1]+"\\"+path[2]
plt.figure("S21_amp")
plt.plot(res_freqs, 20*np.log10(res_data[0]))
plt.savefig(fig_path+"\\S21_amp.png", format= "png")
plt.close()
plt.figure("S21_ph")
plt.plot(res_freqs, res_data[1])
plt.savefig(fig_path+"\\S21_phase.png", format= "png")
plt.close()
save_pkl({"type":"S21_out_of_center_anticross_i-51_5"}, {"F":res_freqs, "S21":res_data, "P":-30}, plot=False)
plt.ion()

In [ ]:
currents = np.linspace(-290e-6, -260e-6, 101)
pna.set_xlim(3.16e9, 3.20e9)
pna.set_bandwidth(10)
pna.set_averages(1)
pna.set_nop(201)
pna.set_power(-25)
sweep.sweep(pna, (currents, current_src.set_current, 'Coil current'), filename='Acouston_2 spectrum_-25dB')

In [14]:
currents = np.linspace(0e-6, 300e-6, 301)
#freqs = np.linspace(3e9,4e9, 51)
pna.set_nop(1)
lo1.set_status(1)
lo1.set_frequency(3.8e9)
pna.set_xlim(3.176453e9, 3.176453e9)
pna.set_bandwidth(10)
pna.set_averages(1)
pna.set_power(-25)
sweep.sweep(pna, (currents, current_src.set_current, 'Coil current'), \
                 filename='Acouston_2 spectrum_-25dB')

Started at:  May 15 2017 12:54:32
First sweep...

c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Coil current: 0.0003,	average cycle time: 0.56s	6s		
Elapsed time: 0 h 2 m 49.98 s


{'S-parameter': (('Coil current',),
  (array([  0.00000000e+00,   1.00000000e-06,   2.00000000e-06,
            3.00000000e-06,   4.00000000e-06,   5.00000000e-06,
            6.00000000e-06,   7.00000000e-06,   8.00000000e-06,
            9.00000000e-06,   1.00000000e-05,   1.10000000e-05,
            1.20000000e-05,   1.30000000e-05,   1.40000000e-05,
            1.50000000e-05,   1.60000000e-05,   1.70000000e-05,
            1.80000000e-05,   1.90000000e-05,   2.00000000e-05,
            2.10000000e-05,   2.20000000e-05,   2.30000000e-05,
            2.40000000e-05,   2.50000000e-05,   2.60000000e-05,
            2.70000000e-05,   2.80000000e-05,   2.90000000e-05,
            3.00000000e-05,   3.10000000e-05,   3.20000000e-05,
            3.30000000e-05,   3.40000000e-05,   3.50000000e-05,
            3.60000000e-05,   3.70000000e-05,   3.80000000e-05,
            3.90000000e-05,   4.00000000e-05,   4.10000000e-05,
            4.20000000e-05,   4.30000000e-05,   4.40000000e-05,
    

In [6]:
current_src.set_current(250e-6)
freqs = np.linspace(1.0e9,2.5e9, 1501)
pna.set_nop(1)
lo1.set_status(1)
lo1.set_power(18)
pna.set_xlim(3.1763e9, 3.1763e9)
pna.set_bandwidth(2)
pna.set_averages(1)
pna.set_power(-35)

sweep.sweep(pna, (freqs, lo1.set_frequency, 'Excitation frequency'), \
                 filename='2 Tone spectrum as a function of excitation freqeuncy')

Started at:  May 15 2017 20:00:33


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 0 m 0.0 s,	parameter values: Excitation frequency: 2.5e+09,	average cycle time: 0.83s	3s			
Elapsed time: 0 h 20 m 40.86 s


{'S-parameter': (('Excitation frequency',),
  (array([  1.00000000e+09,   1.00100000e+09,   1.00200000e+09, ...,
            2.49800000e+09,   2.49900000e+09,   2.50000000e+09]),),
  array([ 0.00032144-0.00160752j,  0.00038011-0.00165235j,
          0.00037923-0.00161627j, ...,  0.00031996-0.00167433j,
          0.00024652-0.00161513j,  0.00029603-0.00160541j]),
  {'log': 20})}

In [16]:
#current_src.set_current(155e-6)
currents = np.linspace(150e-6, 350e-6, 51)
#powers = np.linspace(-15, 5, 41)
lo1.set_power(18)
freqs = np.linspace(1.5e9,3.5e9,51)
pna.set_nop(1)
lo1.set_status(1)
pna.set_xlim(3.1766e9, 3.1766e9)
pna.set_bandwidth(2)
pna.set_averages(1)
pna.set_power(-35)

sweep.sweep(pna, (currents, current_src.set_current, 'Current'), \
                 (freqs, lo1.set_frequency, 'Excitation frequency'), \
                 filename='Two-Tone Spectrum')

Started at:  May 15 2017 19:45:53


c:\python36\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 44 m 7.01 s,	parameter values: Current: 0.00015,	Excitation frequency: 2.62e+09,	average cycle time:    1s		

KeyboardInterrupt: 

In [9]:
pna.set_nop(1)
pna.set_xlim(3.176453e9, 3.176453e9)
current_src.set_current(100e-6)

True

In [ ]:
powers = np.arange(-10,15,1.)
freq_2tone = np.linspace(3e9,5e9, 201)
sweep.sweep(pna, (powers, lo1.set_power, 'lo1 power'), 
            (freq_2tone, lo1.set_frequency, 'Exitation Frequency'), filename='Acoustic acousmons 2tone_power_sweep')

# 2tone spectroscopy

In [ ]:
pna.set_xlim(3.176453e9, 3.176453e9)
pna.set_bandwidth(10)
pna.set_averages(1)
pna.set_nop(1)
pna.set_power(-20)

In [ ]:
lo1.set_status(1)

In [ ]:
freq_2tone = np.linspace(3.12e9, 3.25e9, 31)
lo1.set_power(5)
currents = np.linspace(-50e-6, -40e-6, 31)

In [ ]:
%matplotlib

In [ ]:
sweep.sweep(pna, (currents, current_src.set_current, 'Coil current'), (freq_2tone, lo1.set_frequency, 'Exitation Frequency'),
            filename='Acouston_2_2tone_spectrum_-20dB_exc_5')

### Загрузка данных

In [ ]:
filename = 'S-parameter WTJPA Ic6.9uAC3.6pF spectrum'
location = 'D:\\qtlab\\ReiData\\data\\2017-04-28\\19-17-33'
data = load_pkl(filename, location=location)[1]

In [ ]:
S21 = data['S-parameter'][2]
currents = data['S-parameter'][1][0]
frequencies = data['S-parameter'][1][1]
fitresults = []

In [ ]:
for cur_id, cur in enumerate(currents):
    fitter = circuit.reflection_port(f_data=frequencies, z_data_raw=S21[cur_id,:])
    fitresults.append(fitter.autofit())

In [ ]:
plt.plot(np.real(S21[0,:]))

In [ ]:
filename = 'S-parameter WTJPA Ic6.9uAC3.6pF spectrum'
location = 'D:\\qtlab\\ReiData\\data\\2017-04-28\\19-17-33'
data = load_pkl(filename, location=location)[1]

# Acous

In [ ]:
#center

In [123]:
filename = 'S21_out_of_center_anticross_i-53'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-11\\01-35-43'
data_1 = load_pkl(filename, location=location)

D:\qtlab\ReiData\data\2017-05-11\01-35-43/S21_out_of_center_anticross_i-53.pkl


In [ ]:
#out_of_center

In [ ]:
filename = 'S21_out_of_center_anticross_i-51_5'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-11\\01-52-29'
data_2 = load_pkl(filename, location=location)

In [124]:
data_1

(2, {'F': array([  3.14645300e+09,   3.14650300e+09,   3.14655300e+09, ...,
           3.20635300e+09,   3.20640300e+09,   3.20645300e+09]),
  'P': -30,
  'S21': (array([  2.54640877e-04,   3.15163420e-04,   2.57904296e-04, ...,
            4.87903409e-05,   3.52490497e-05,   4.26986820e-05]),
   array([-0.37663709, -0.25212261, -0.42102975, ..., -0.5511268 ,
          -0.60294854, -0.79904707]))}, {'type': 'S21_out_of_center_anticross_i-53'})

In [ ]:
S21_1 = data_1[1]['S21']
frequencies_1 = data_1[1]['F']

In [ ]:
S21_11 = data_1[0]['S21']
frequencies_1 = data_1[1]['F']

In [ ]:
S21_2 = data_2[1]['S21']
frequencies_2 = data_2[1]['F']

In [ ]:
frequencies_2

In [ ]:
plt.plot(frequencies_2,S21_1[0]/S21_2[0])

In [ ]:
plt.figure("Dispers_shift")
plt.plot(frequencies_2, S21_1[0]-S21_2[0])

In [ ]:
plt.ioff()
path = get_location()
mk_dir()
fig_path = path[0]+"\\"+path[1]+"\\"+path[2]
plt.figure("S21_anticross-non_anticross")
plt.plot(res_freqs, S21_1[0]-S21_2[0])
plt.savefig(fig_path+"\\S21_amp_d_shift.png", format= "png")
plt.close()
save_pkl({"type":"S21_center-out_anticross"}, {"F":res_freqs, "S21":S21_1[0]-S21_2[0], "P":-30}, plot=False)
plt.ion()

In [ ]:
filename = 'S21_center-out_anticross'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-11\\00-44-48'
data_1 = load_pkl(filename, location=location)

In [ ]:
S21_3 = data_1[1]['S21']
frequencies_3 = data_1[1]['F']

In [ ]:
S21_3


In [ ]:
plt.plot(frequencies_2, S21_3)

In [ ]:
plt.figure("Check")
plt.plot(frequencies_2, S21_1[0])
plt.plot(frequencies_2, S21_2[0])
plt.plot(frequencies_2, S21_1[0]-S21_2[0])

In [23]:
# trahsfer to .mat

In [11]:
filename = 'S-parameter anticrossing_p_-50dbm'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-16\\18-11-12'
data_1 = load_pkl(filename, location=location)

D:\qtlab\ReiData\data\2017-05-16\18-11-12/S-parameter anticrossing_p_-50dbm.pkl


In [13]:
data_1

(2,
 {'S-parameter': (('Coil current', 'Frequency'),
   (array([  3.00000000e-05,   3.01000000e-05,   3.02000000e-05,
             3.03000000e-05,   3.04000000e-05,   3.05000000e-05,
             3.06000000e-05,   3.07000000e-05,   3.08000000e-05,
             3.09000000e-05,   3.10000000e-05,   3.11000000e-05,
             3.12000000e-05,   3.13000000e-05,   3.14000000e-05,
             3.15000000e-05,   3.16000000e-05,   3.17000000e-05,
             3.18000000e-05,   3.19000000e-05,   3.20000000e-05,
             3.21000000e-05,   3.22000000e-05,   3.23000000e-05,
             3.24000000e-05,   3.25000000e-05,   3.26000000e-05,
             3.27000000e-05,   3.28000000e-05,   3.29000000e-05,
             3.30000000e-05,   3.31000000e-05,   3.32000000e-05,
             3.33000000e-05,   3.34000000e-05,   3.35000000e-05,
             3.36000000e-05,   3.37000000e-05,   3.38000000e-05,
             3.39000000e-05,   3.40000000e-05,   3.41000000e-05,
             3.42000000e-05,   3.4300

In [14]:
import numpy, scipy.io
scipy.io.savemat('D:\\qtlab\\ReiData\\data\\2017-05-16\\18-11-12\\S21_1D_-50.mat', mdict={'S21vsF': data_1[1]})

# Cutting plot

In [107]:
filename = 'S-parameter anticrossing'
location = 'D:\\qtlab\\ReiData\\data\\2017-05-11\\19-21-15'
data_1 = load_pkl(filename, location=location)

D:\qtlab\ReiData\data\2017-05-11\19-21-15/S-parameter anticrossing.pkl


In [108]:
data_1

(2,
 {'S-parameter': (('Coil current', 'Frequency'),
   (array([ -5.20000000e-05,  -5.19500000e-05,  -5.19000000e-05,
            -5.18500000e-05,  -5.18000000e-05,  -5.17500000e-05,
            -5.17000000e-05,  -5.16500000e-05,  -5.16000000e-05,
            -5.15500000e-05,  -5.15000000e-05,  -5.14500000e-05,
            -5.14000000e-05,  -5.13500000e-05,  -5.13000000e-05,
            -5.12500000e-05,  -5.12000000e-05,  -5.11500000e-05,
            -5.11000000e-05,  -5.10500000e-05,  -5.10000000e-05,
            -5.09500000e-05,  -5.09000000e-05,  -5.08500000e-05,
            -5.08000000e-05,  -5.07500000e-05,  -5.07000000e-05,
            -5.06500000e-05,  -5.06000000e-05,  -5.05500000e-05,
            -5.05000000e-05,  -5.04500000e-05,  -5.04000000e-05,
            -5.03500000e-05,  -5.03000000e-05,  -5.02500000e-05,
            -5.02000000e-05,  -5.01500000e-05,  -5.01000000e-05,
            -5.00500000e-05,  -5.00000000e-05,  -4.99500000e-05,
            -4.99000000e-05,  -4.9850

In [109]:
S21 = data_1[1]['S-parameter'][2]
f = data_1[1]['S-parameter'][1][1]
I = data_1[1]['S-parameter'][1][0]
print (f.shape, I.shape, S21.shape)

(200,) (201,) (201, 200)


In [110]:
plt.pcolormesh(I, f, np.abs(S21.T))

In [114]:
I_ind = np.argmin(np.abs(I))
plt.figure('Abs')
plt.plot(f, np.abs(S21[[0, 100, 200],:]).T)
plt.figure('Phase')
plt.plot(f, np.unwrap(np.angle(S21[[0, 100, 200],:])).T)

# Flux periodicity

In [2]:
import pickle
import matplotlib.pyplot as plt
data = pickle.load(open('D:\\qtlab\\ReiData\\data\\2017-05-02\\17-20-11\\S-parameter Acouston_2 spectrum.pkl', 'rb'))
plt.pcolormesh(data[1]['S-parameter'][1][0], data[1]['S-parameter'][1][1], np.abs(data[1]['S-parameter'][2]-np.mean(data[1]['S-parameter'][2], axis=0)).T)

In [12]:
plt.plot(data[1]['S-parameter'][1][0], np.sum(np.abs(data[1]['S-parameter'][2]-np.mean(data[1]['S-parameter'][2], axis=0)), axis=1))
plt.grid()

In [40]:
data_mmplx = pickle.load(open('D:\\Measurement-automation\\data\\M-M MPLX 1\\May 03 2017\\14-41-25 - IV-anticrossing\\IV-anticrossing_raw_data.pkl', 'rb'))
plt.plot(data_mmplx['frequency'], np.gradient(np.unwrap(-np.angle(np.mean(data_mmplx['data'], axis=0))))/(2*np.pi*(data_mmplx['frequency'][1]-data_mmplx['frequency'][0])))
plt.grid()
plt.title('Electric delay, s')

Text(0.5,1,'Electric delay, s')

In [19]:
data_mmplx['']

dict_keys(['current', 'data', 'frequency'])